/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2024-10-09 13:49:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Desktop/exercicio1-assistencia/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/assistenciaInfo/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664464278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1728160573843L));
    _jspx_dependants.put("jar:file:/C:/Users/Usuario/Desktop/exercicio1-assistencia/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/assistenciaInfo/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664464278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/home.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<title>Exercício Prático 1</title>\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("    background: url('img/background.jpg') no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header{\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 20px 100px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    color: white;\r\n");
      out.write("    user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navegation  a{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 1.1em;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navegation a::after{\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    bottom: -6px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 10%;\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transform-origin: right;\r\n");
      out.write("    transform: scaleX(0);\r\n");
      out.write("    transition: transform .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navegation a:hover::after{\r\n");
      out.write("    transform-origin: left;\r\n");
      out.write("    transform: scaleX(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navegation .btn-login{\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    font-size: 1.1em;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    width: 130px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: 2px solid white;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: white;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navegation .btn-login:hover{\r\n");
      out.write("    background: white;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    height: 440px;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: 2px solid rgba(255, 255, 255, .5);\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    backdrop-filter: blur(20px);\r\n");
      out.write("    box-shadow: 0 0 30px rgba(0, 0, 0, .5);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    transform: scale(0);\r\n");
      out.write("    transition: transform .5s ease, height .2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper.active-popup{\r\n");
      out.write("    transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper.active{    \r\n");
      out.write("    height: 650px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-box{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-box.login{\r\n");
      out.write("    transition: transform .18s ease;\r\n");
      out.write("    transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper.active .form-box.login{\r\n");
      out.write("    transition: none;\r\n");
      out.write("    transform: translateX(-400px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-box.register{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    transition: none;\r\n");
      out.write("    transform: translateX(400px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper.active .form-box.register{\r\n");
      out.write("    transition: transform .18s ease;\r\n");
      out.write("    transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .icon-close{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    background: #162938;\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    color: white;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    border-bottom-left-radius: 20px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-box h2{\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-box{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    border-bottom: 2px solid #162938;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-box label{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 5px;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    pointer-events: none;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-box input:focus~label, .input-box input:not(:placeholder-shown)~label{\r\n");
      out.write("    top: -5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-box input{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    padding: 0 35px 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-box .icon{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 8px;\r\n");
      out.write("    font-size: 1.2em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    line-height: 57px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remember-forgot{\r\n");
      out.write("    font-size: .9em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin: -15px 0 15px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remember-forgot label input{\r\n");
      out.write("    accent-color: #162938;\r\n");
      out.write("    margin-right: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remember-forgot a{\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".remember-forgot a:hover{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    background: #162938;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-register {\r\n");
      out.write("    font-size: .9em;\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    margin: 25px 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-register p a {\r\n");
      out.write("    color: #162938;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-register p a:hover{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alerts-container {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    z-index: 100;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"alerts-container\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<header>\r\n");
      out.write("        <h2 class=\"logo\">Logo</h2>\r\n");
      out.write("        <nav class=\"navegation\">\r\n");
      out.write("            <a href=\"#\">Home</a>\r\n");
      out.write("            <a href=\"#\">About</a>\r\n");
      out.write("            <a href=\"#\">Contact us</a>\r\n");
      out.write("            <button class=\"btn-login\">Login</button>\r\n");
      out.write("        </nav>\r\n");
      out.write("</header>\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <span class=\"icon-close\">\r\n");
      out.write("            <ion-icon name=\"close\"></ion-icon>\r\n");
      out.write("        </span>\r\n");
      out.write("		\r\n");
      out.write("        <div class=\"form-box login\">\r\n");
      out.write("            <h2>Login</h2>\r\n");
      out.write("            <form action=\"clienteLogin\" method=\"post\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"mail\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\" required>\r\n");
      out.write("                    <label for=\"email\">Email*</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"lock-closed\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"password\" required>\r\n");
      out.write("                    <label for=\"password\">Senha*</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"remember-forgot\">\r\n");
      out.write("                    <label><input type=\"checkbox\">Remember me</label>\r\n");
      out.write("                    <a href=\"#\">Esqueci minha senha</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn\">Login</button>\r\n");
      out.write("                <div class=\"login-register\">\r\n");
      out.write("                    <p>Não tem conta? <a href=\"#\" class=\"register-link\">Cadastrar</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-box register\">\r\n");
      out.write("            <h2>Cadastro</h2>\r\n");
      out.write("            <form action=\"clienteRegister\" method=\"post\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"person\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" id=\"name\" minlength=\"3\" maxlength=\"50\" required> <span id=\"0\"></span>\r\n");
      out.write("                    <label for=\"name\">Nome Completo*</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"mail\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\" required> <span id=\"1\"></span>\r\n");
      out.write("                    <label for=\"email\">Email*</label> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"call-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"text\" name=\"phone\" id=\"phone\" required> <span id=\"2\"></span>\r\n");
      out.write("                    <label for=\"phone\">Telefone*</label> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"id-card-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"text\" name=\"cpf\" id=\"cpf\" required> <span id=\"3\"></span>\r\n");
      out.write("                    <label for=\"cpf\">CPF*</label> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"lock-closed\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"password\" required> <span id=\"4\"></span>\r\n");
      out.write("                    <label for=\"password\">Senha*</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"remember-forgot\">\r\n");
      out.write("                    <label><input type=\"checkbox\">Eu concordo com os termos</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn\">Cadastrar</button>\r\n");
      out.write("                <div class=\"login-register\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        já tenho conta? <a href=\"#\" class=\"login-link\">Login</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"module\" src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("<script nomodule src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /home.jsp(297,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result == 'registered'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("                    Usuário cadastrado com sucesso. Faça o login.\r\n");
          out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /home.jsp(303,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result == 'loginError'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("                    E-mail e/ou senha inválidos.\r\n");
          out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /home.jsp(310,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result == 'notRegistered'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("                E-mail já cadastrado. Tente novamente.\r\n");
          out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("            </div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
